Repository AryanK1511/github-echo, pull requests merged in 2024-09, with the labels that each got.

#2 Setup basic directory structure
  Pipfile
  Pipfile.lock
  _config.py
  _docs/resources.md
  _main.py
  application/__init__.py
  application/utils/gemini_model.py
  main.py
  setup.py
Labels: documentation, enhancement

#4 Configured Google Gemini API
  Pipfile
  Pipfile.lock
  _config.py
  _docs/resources.md
  application/core/gemini_model.py
  application/utils/gemini_model.py
Labels: enhancement

#7 Add GitHub data fetching feature
  Pipfile.lock
  application/core/github_api.py
Labels: enhancement

#14 Added `--output` and `--version` flags and also made it look pretty and user friendly with messages for the user and a progress bar.
  Pipfile
  Pipfile.lock
  _docs/resources.md
  _docs/using_pipenv.md
  _main.py
  application/core/gemini_model.py
  application/utils/api.py
  application/utils/callbacks.py
  application/utils/gemini_config.py
  application/utils/parser.py
Labels: enhancement

#15 Setup error handling
  _main.py
  application/core/github_api.py
  application/utils/callbacks.py
  application/utils/parser.py
  setup.py
Labels: enhancement

#17 Add basic CI pipeline for linting
  .github/workflows/ci.yml
Labels: enhancement

#18 Add a descriptive README.md file and configure MD formatter
  .vscode/settings.json
  README.md
  assets/logo.png
Labels: documentation

#21 Configure packaging scripts and update all docs
  MANIFEST.in
  Pipfile
  Pipfile.lock
  README.md
  _config.py
  _docs/distribution_commands.md
  _docs/linting.md
  _docs/resources.md
  _docs/using_pipenv.md
  _main.py
  application/core/gemini_model.py
  application/core/github_api.py
  application/utils/callbacks.py
  pyproject.toml
Labels: documentation, enhancement

#23 Resolved top-level import
  _config.py
Labels: enhancement

#24 Prepare release 0.0.1
  application/utils/callbacks.py
  pyproject.toml
Labels: enhancement

#25 Prepare release 0.0.1
  README.md
  pyproject.toml
Labels: enhancement

#31 Migrated from using `pipenv` to `poetry` for dependency management
  Pipfile
  Pipfile.lock
  README.md
  _docs/distribution_commands.md
  _docs/resources.md
  _docs/using_poetry.md
  application/utils/callbacks.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#32 Initialize `pytest` for testing and add testing job to the CI pipeline
  .github/workflows/ci.yml
  application/utils/callbacks.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/fixtures.py
  tests/unit/test_cli_features.py
Labels: enhancement

#33 Dockerized the application
  .github/workflows/ci.yml
  Dockerfile
  MANIFEST.in
  README.md
Labels: documentation, enhancement

#35 Allow user to control the temperature of the underlying ML model via command line arguments
  README.md
  _main.py
  application/core/gemini_model.py
  application/utils/callbacks.py
  application/utils/gemini_config.py
Labels: documentation, enhancement

#38 enhancement/issue-37
  .gitignore
  README.md
  _main.py
  application/core/gemini_model.py
  application/utils/gemini_config.py
  application/utils/parser.py
  poetry.lock
  tests/unit/test_structured_output.py
Labels: enhancement

#43 Replace progress bar with spinner
  _main.py
  application/utils/callbacks.py
Labels: bug
